### ISSUE TITLE
Error when running example: Class extends value #<Object> is not a constructor or null

### ISSUE THREAD

**Issue by mef** [justinmahar/articulate-nlg#1]
The example code crashes with the following error, whenever executed directly with node.js.

```
class Dog extends Persona {
                  ^

TypeError: Class extends value #<Object> is not a constructor or null
```

This happens in node.js, at least in versions v14, v16 and v18. 

### How to reproduce the bug

1. copy/paste the example code from README.md in a Javascript file (e.g. `demo.js`)
2. run this javascript file with node .js (`node demo.js`)

### Resolution

One way to fix the problem is to change the code as shown below:

```diff
import Persona from "articulate-nlg";

- class Dog extends Persona
+ class Dog extends Persona.default
  createVocab = () => {
    // Persona helper functions, for convenience.
    const say = this.say;
```

### Example code works in some different context(s)

Copy-pasting the exact same example code inside a `svelte.js` component runs well, and does not require to append `.default`.

Edit: added steps to reproduce and precisions about when the bug occurs.

**Comment by justinmahar** [comment]
Hey @mef! Thanks for pointing this out. So the main problem in some environments seems to stem from the default export not being named. So, I've changed it to a named export and updated the major version and docs to reflect this.

In v3 and on, you import a Persona like so:

```js
import { Persona } from "articulate-nlg";
```

This should do the trick!

To get the latest update and try it out:

```bash
npm install articulate-nlg@latest
```

Give that a shot and let me know how it goes!

**Comment by mef** [comment]
Hi, I just tested, it works like a charm, thanks!

**Comment by justinmahar** [comment]
Woohoo! Curious, what are you building?

**Comment by mef** [comment]
> Curious, what are you building?

I'm generating a narrative description of surf forecasting data, for my side-project [gonna.surf](https://gonna.surf), and am currently evaluating a few options for the NLG.

I start by  computing some statistics on the hourly data retrieved from the weather agency. Then from the set of measures obtained, my goal is to get a written form, like:

> There will be some small waves tomorrow morning (1m in average), then a Northern swell will reach the coast in the afternoon, and the wave size will increase from 1.4m to 2.1m.

I'm not sure yet about the added value of an NLG library, versus using javascript template literals. In articulate-nlg, I understand that `ifElse` is limited to checking the (truthy) existence of a param, but cannot evaluate expressions, so logic needs to be incorporated outside of articulate:

```
let veryWindy = windSpeed >= 30 ? true : false

friend.articulate('wind', {veryWindy: veryWindy, windSpeed: windSpeed})
```

Or am I missing something?

**Comment by justinmahar** [comment]
Pretty awesome side project!

That's correct. At least, the library doesn't internally support comparison logic. You'd need to evaluate that logic outside the library and pass in the result, like your example shows. 

The added value of this library would probably be randomness in the responses. You could `choose()` or `cycle()` different responses to make the output different every time given the same inputs.

Good luck with your project!
